import type { RegistryCase } from "./types";

/**
 * The case registry — ingested from the source spreadsheet
 * "Cases for the platform.xlsx". Official names are single strings (identical
 * in both locales); types, statuses and notes are localised. `lit` marks cases
 * that already have a written summary. This is the primary content the future
 * Payload admin will edit.
 */
export const registryCases: RegistryCase[] = [
  {
    id: "icj-1",
    num: 1,
    institutionId: "icj",
    name: "Application of the International Convention for the Suppression of the Financing of Terrorism and of the International Convention on the Elimination of All Forms of Racial Discrimination (Ukraine v. Russian Federation), Judgment, I.C.J. Reports 2024, 31 January 2024",
    type: { uk: "Міжнародне публічне", en: "Public international law" },
    statusKey: "decided",
    status: { uk: "Рішення винесено", en: "Judgment delivered" },
    year: 2017,
    amountUsd: null,
    note: { uk: "ICJ GL 166 · Крим, Донбас", en: "ICJ GL 166 · Crimea, Donbas" },
    pages: 213,
    decisionUrl: "https://www.icj-cij.org/sites/default/files/case-related/166/166-20240131-jud-01-00-en.pdf",
    summarySlug: "icj-cerd-icsft",
    lit: true,
  },
  {
    id: "icj-2",
    num: 2,
    institutionId: "icj",
    name: "Allegations of Genocide under the Convention on the Prevention and Punishment of the Crime of Genocide (Ukraine v. Russian Federation: 32 States intervening), Preliminary Objections, Judgment, I.C.J. Reports 2024, 2 February 2024",
    type: { uk: "Міжнародне публічне", en: "Public international law" },
    statusKey: "warrant",
    status: { uk: "Розгляд по суті, є ордер", en: "Merits pending; warrant issued" },
    year: 2022,
    amountUsd: null,
    note: { uk: "ICJ GL 182", en: "ICJ GL 182" },
    pages: 70,
    decisionUrl: "https://www.icj-cij.org/sites/default/files/case-related/182/182-20240202-jud-01-00-en.pdf",
    summarySlug: "icj-genocide",
    lit: true,
  },
  {
    id: "icj-3",
    num: 3,
    institutionId: "icj",
    name: "Appeal from the ICAO Council Decision dated 30 June 2025 (Russian Federation v. Australia and Netherlands)",
    type: { uk: "Міжнародне публічне", en: "Public international law" },
    statusKey: "progress",
    status: { uk: "Попередній етап, рішення нема, лише процедурні ордери", en: "Preliminary stage; procedural orders only" },
    year: 2025,
    amountUsd: null,
    note: { uk: "ICJ GL 201", en: "ICJ GL 201" },
    pages: null,
    decisionUrl: "https://www.icj-cij.org/case/201",
    lit: false,
  },
  {
    id: "ecthr-4",
    num: 4,
    institutionId: "ecthr",
    name: "Ukraine v Russia (re Crimea) [GC]",
    type: { uk: "Права людини", en: "Human rights" },
    statusKey: "decided",
    status: { uk: "Рішення винесено", en: "Judgment delivered" },
    year: 2014,
    amountUsd: null,
    note: { uk: "Apps 20958/14, 38334/18", en: "Apps 20958/14, 38334/18" },
    pages: null,
    decisionUrl: "https://hudoc.echr.coe.int/eng#{%22appno%22:[%2220958/14%22],%22itemid%22:[%22001-235139%22]}",
    lit: false,
  },
  {
    id: "ecthr-5",
    num: 5,
    institutionId: "ecthr",
    name: "Ukraine and Netherlands v Russia [GC] — MH17 + схід",
    type: { uk: "Права людини", en: "Human rights" },
    statusKey: "decided",
    status: { uk: "Очікує сатисфакції", en: "Awaiting just satisfaction" },
    year: 2014,
    amountUsd: null,
    note: { uk: "Apps 8019/16 et al.", en: "Apps 8019/16 et al." },
    pages: 304,
    decisionUrl: "https://hudoc.echr.coe.int/eng#{%22appno%22:[%2243800/14%22],%22itemid%22:[%22001-244292%22]}",
    lit: false,
  },
  {
    id: "ecthr-8",
    num: 8,
    institutionId: "ecthr",
    name: "Russia v Ukraine no. 36958/21",
    type: { uk: "Права людини", en: "Human rights" },
    statusKey: "rejected",
    status: { uk: "Відхилено (Правило 39)", en: "Rule 39 request rejected" },
    year: 2021,
    amountUsd: null,
    note: { uk: "App 36958/21", en: "App 36958/21" },
    pages: null,
    decisionUrl: "https://www.echr.coe.int/w/russia-v-ukraine-no-36958/21-",
    lit: false,
  },
  {
    id: "icc-situation",
    num: null,
    institutionId: "icc",
    name: "Situation in Ukraine",
    type: { uk: "Кримінальне", en: "Criminal" },
    statusKey: "progress",
    status: { uk: "Розслідування", en: "Investigation" },
    year: 2022,
    amountUsd: null,
    note: { uk: "ICC-01/22", en: "ICC-01/22" },
    pages: null,
    decisionUrl: "https://www.icc-cpi.int/situations/ukraine",
    lit: false,
  },
  {
    id: "icc-9",
    num: 9,
    institutionId: "icc",
    name: "Putin",
    type: { uk: "Кримінальне", en: "Criminal" },
    statusKey: "warrant",
    status: { uk: "Ордер видано", en: "Warrant issued" },
    year: 2023,
    amountUsd: null,
    note: { uk: "депортації населення (дітей) та незаконного переміщення населення (дітей) з окупованих територій України до Російської Федерації (відповідно до статей 8(2)(a)(vii) та 8(2)(b)(viii) Римського статуту", en: "Deportation and unlawful transfer of children from occupied territories of Ukraine to Russia (arts. 8(2)(a)(vii) & 8(2)(b)(viii) of the Rome Statute)" },
    pages: null,
    decisionUrl: "https://www.icc-cpi.int/defendant/vladimir-vladimirovich-putin",
    lit: false,
  },
  {
    id: "icc-10",
    num: 10,
    institutionId: "icc",
    name: "Lvova-Belova",
    type: { uk: "Кримінальне", en: "Criminal" },
    statusKey: "warrant",
    status: { uk: "Ордер видано", en: "Warrant issued" },
    year: 2023,
    amountUsd: null,
    note: { uk: "депортації населення (дітей) та незаконного переміщення населення (дітей) з окупованих територій України до Російської Федерації (відповідно до статей 8(2)(a)(vii) та 8(2)(b)(viii) Римського статуту", en: "Deportation and unlawful transfer of children from occupied territories of Ukraine to Russia (arts. 8(2)(a)(vii) & 8(2)(b)(viii) of the Rome Statute)" },
    pages: null,
    decisionUrl: "https://www.icc-cpi.int/defendant/maria-alekseyevna-lvova-belova",
    lit: false,
  },
  {
    id: "icc-11",
    num: 11,
    institutionId: "icc",
    name: "Kobylash",
    type: { uk: "Кримінальне", en: "Criminal" },
    statusKey: "warrant",
    status: { uk: "Ордер видано", en: "Warrant issued" },
    year: 2024,
    amountUsd: null,
    note: { uk: "Воєнні злочини: Cпрямування нападів на цивільні об'єкти (стаття 8(2)(b)(ii) заподіяння надмірної випадкової шкоди цивільному населенню або пошкодженням цивільних об'єктів (стаття 8(2)(b)(iv), а також за злочин проти людяності у вигляді нелюдських дій згідно зі статтею 7(1)(k) Римського статуту.", en: "War crimes: directing attacks against civilian objects (art. 8(2)(b)(ii)); excessive incidental civilian harm (art. 8(2)(b)(iv)); crime against humanity of inhumane acts (art. 7(1)(k)) of the Rome Statute." },
    pages: null,
    decisionUrl: "https://www.icc-cpi.int/defendant/sergei-ivanovich-kobylash",
    lit: false,
  },
  {
    id: "icc-12",
    num: 12,
    institutionId: "icc",
    name: "Sokolov",
    type: { uk: "Кримінальне", en: "Criminal" },
    statusKey: "warrant",
    status: { uk: "Ордер видано", en: "Warrant issued" },
    year: 2024,
    amountUsd: null,
    note: { uk: "Воєнні злочини: Cпрямування нападів на цивільні об'єкти (стаття 8(2)(b)(ii) заподіяння надмірної випадкової шкоди цивільному населенню або пошкодженням цивільних об'єктів (стаття 8(2)(b)(iv), а також за злочин проти людяності у вигляді нелюдських дій згідно зі статтею 7(1)(k) Римського статуту.", en: "War crimes: directing attacks against civilian objects (art. 8(2)(b)(ii)); excessive incidental civilian harm (art. 8(2)(b)(iv)); crime against humanity of inhumane acts (art. 7(1)(k)) of the Rome Statute." },
    pages: null,
    decisionUrl: "https://www.icc-cpi.int/defendant/viktor-nikolayevich-sokolov",
    lit: false,
  },
  {
    id: "icc-13",
    num: 13,
    institutionId: "icc",
    name: "Shoigu",
    type: { uk: "Кримінальне", en: "Criminal" },
    statusKey: "warrant",
    status: { uk: "Ордер видано", en: "Warrant issued" },
    year: 2024,
    amountUsd: null,
    note: { uk: "Воєнні злочини: Cпрямування нападів на цивільні об'єкти (стаття 8(2)(b)(ii) заподіяння надмірної випадкової шкоди цивільному населенню або пошкодженням цивільних об'єктів (стаття 8(2)(b)(iv), а також за злочин проти людяності у вигляді нелюдських дій згідно зі статтею 7(1)(k) Римського статуту.", en: "War crimes: directing attacks against civilian objects (art. 8(2)(b)(ii)); excessive incidental civilian harm (art. 8(2)(b)(iv)); crime against humanity of inhumane acts (art. 7(1)(k)) of the Rome Statute." },
    pages: null,
    decisionUrl: "https://www.icc-cpi.int/defendant/shoigu",
    lit: false,
  },
  {
    id: "icc-14",
    num: 14,
    institutionId: "icc",
    name: "Gerasimov",
    type: { uk: "Кримінальне", en: "Criminal" },
    statusKey: "warrant",
    status: { uk: "Ордер видано", en: "Warrant issued" },
    year: 2024,
    amountUsd: null,
    note: { uk: "Воєнні злочини: Cпрямування нападів на цивільні об'єкти (стаття 8(2)(b)(ii) заподіяння надмірної випадкової шкоди цивільному населенню або пошкодженням цивільних об'єктів (стаття 8(2)(b)(iv), а також за злочин проти людяності у вигляді нелюдських дій згідно зі статтею 7(1)(k) Римського статуту.", en: "War crimes: directing attacks against civilian objects (art. 8(2)(b)(ii)); excessive incidental civilian harm (art. 8(2)(b)(iv)); crime against humanity of inhumane acts (art. 7(1)(k)) of the Rome Statute." },
    pages: null,
    decisionUrl: "https://www.icc-cpi.int/defendant/gerasimov",
    lit: false,
  },
  {
    id: "itlos-15",
    num: 15,
    institutionId: "itlos",
    name: "Detention of Ukrainian Naval Vessels (ITLOS/PCA) Тимчасові заходи: Case Concerning the Detention of Three Ukrainian Naval Vessels (Ukraine v. Russian Federation), Provisional Measures, Order of 25 May 2019, ITLOS Case No. 26 Арбітраж по суті за додатком VII UNCLOS: Dispute Concerning the Detention of Ukrainian Naval Vessels and Servicemen (Ukraine v. The Russian Federation), PCA Case No. 2019-28",
    type: { uk: "Морське право", en: "Law of the sea" },
    statusKey: "progress",
    status: { uk: "Розгляд по суті", en: "Merits pending" },
    year: 2019,
    amountUsd: null,
    note: { uk: "ITLOS 26", en: "ITLOS 26" },
    pages: null,
    decisionUrl: "https://www.itlos.org/fileadmin/itlos/documents/cases/26/published/C26_Order_20190525.pdf",
    lit: false,
  },
  {
    id: "icao-16",
    num: 16,
    institutionId: "icao",
    name: "Australia & Netherlands v Russia (ICAO, MH17) Australia and the Netherlands v. Russian Federation, ICAO Council Decision under Article 84 of the Chicago Convention, 12 May 2025 (formal decision document - 30 June 2025)",
    type: { uk: "Міжнародне публічне", en: "Public international law" },
    statusKey: "decided",
    status: { uk: "Рішення (оскаржується)", en: "Decision (under appeal)" },
    year: 2022,
    amountUsd: null,
    note: { uk: "MH17 · Чиказька конвенція, ст. 84", en: "MH17 · Чиказька конвенція, ст. 84" },
    pages: null,
    decisionUrl: "https://www.icao.int/Newsroom/Pages/RU/icao-council-vote-on-flight-mh17-case.aspx",
    lit: false,
  },
  {
    id: "scc-17",
    num: 17,
    institutionId: "scc",
    name: "National Joint Stock Company «Naftogaz of Ukraine» v. PJSC «Gazprom», SCC Arbitration No. V 2014/078/080 - Gas Sales Arbitration",
    type: { uk: "Комерційний арбітраж", en: "Commercial arbitration" },
    statusKey: "settled",
    status: { uk: "Врегульовано 2019", en: "Settled (2019)" },
    year: 2014,
    amountUsd: -2020000000,
    note: { uk: "SCC V 2014-078", en: "SCC V 2014-078" },
    pages: null,
    decisionUrl: "https://jusmundi.com/fr/document/decision/en-national-joint-stock-company-naftogaz-of-ukraine-v-public-joint-stock-company-gazprom-final-award-friday-22nd-december-2017#decision_2415",
    lit: false,
  },
  {
    id: "scc-18",
    num: 18,
    institutionId: "scc",
    name: "National Joint Stock Company «Naftogaz of Ukraine» v. PJSC «Gazprom», SCC Arbitration No. V 2014/129 - Gas Transit Arbitration",
    type: { uk: "Комерційний арбітраж", en: "Commercial arbitration" },
    statusKey: "settled",
    status: { uk: "Врегульовано 2019", en: "Settled (2019)" },
    year: 2014,
    amountUsd: 4630000000,
    note: { uk: "SCC V 2014-129", en: "SCC V 2014-129" },
    pages: null,
    decisionUrl: "https://jusmundi.com/fr/document/decision/en-national-joint-stock-company-naftogaz-of-ukraine-v-public-joint-stock-company-gazprom-final-award-wednesday-28th-february-2018#decision_2416",
    lit: false,
  },
  {
    id: "icc-arb-19",
    num: 19,
    institutionId: "icc-arb",
    name: "National Joint Stock Company «Naftogaz of Ukraine» v. PJSC «Gazprom» (III), ICC Case No. 27245/GL",
    type: { uk: "Комерційний арбітраж", en: "Commercial arbitration" },
    statusKey: "decided",
    status: { uk: "Остаточне рішення", en: "Final award" },
    year: 2022,
    amountUsd: 1370000000,
    note: { uk: "ICC 27245/GL", en: "ICC 27245/GL" },
    pages: null,
    decisionUrl: "https://jusmundi.com/en/document/decision/en-national-joint-stock-company-naftogaz-of-ukraine-v-public-joint-stock-company-gazprom-iii-party-representatives",
    lit: false,
  },
  {
    id: "pca-20",
    num: 20,
    institutionId: "pca",
    name: "NJSC Naftogaz of Ukraine, PJSC State Joint Stock Company Chornomornaftogaz, PJSC Ukrgasvydobuvannya and others v. The Russian Federation, PCA Case No. 2017-16",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "enforcement",
    status: { uk: "Виконання", en: "Enforcement" },
    year: 2016,
    amountUsd: 5000000000,
    note: { uk: "PCA 2017-16", en: "PCA 2017-16" },
    pages: 218,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-21",
    num: 21,
    institutionId: "pca",
    name: "Aeroport Belbek LLC and Mr. Igor Valerievich Kolomoisky v. The Russian Federation, PCA Case No. 2015-07",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "decided",
    status: { uk: "Відповідальність встановлена", en: "Liability established" },
    year: 2015,
    amountUsd: null,
    note: { uk: "PCA 2015-07", en: "PCA 2015-07" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-22",
    num: 22,
    institutionId: "pca",
    name: "PJSC CB PrivatBank and Finance Company Finilon LLC v. The Russian Federation, PCA Case No. 2015-21",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "decided",
    status: { uk: "Відповідальність встановлена", en: "Liability established" },
    year: 2015,
    amountUsd: 1000000000,
    note: { uk: "PCA 2015-21 · заявлена", en: "PCA 2015-21 · claimed" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-23",
    num: 23,
    institutionId: "pca",
    name: "JSC Oschadbank v. The Russian Federation, PCA Case No. 2016-14",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "enforcement",
    status: { uk: "Виконання", en: "Enforcement" },
    year: 2016,
    amountUsd: 1100000000,
    note: { uk: "PCA 2016-14", en: "PCA 2016-14" },
    pages: null,
    decisionUrl: "https://jusmundi.com/en/document/decision/en-oschadbank-v-russian-federation-none-currently-available-friday-1st-january-2016#decision_4484",
    lit: true,
  },
  {
    id: "pca-24",
    num: 24,
    institutionId: "pca",
    name: "PJSC Ukrnafta v. The Russian Federation, PCA Case No. 2015-34",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "decided",
    status: { uk: "Остаточне рішення", en: "Final award" },
    year: 2015,
    amountUsd: 44455012,
    note: { uk: "PCA 2015-34", en: "PCA 2015-34" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-25",
    num: 25,
    institutionId: "pca",
    name: "Stabil LLC, Rubenor LLC, Rustel LLC, Novel-Estate LLC, PII Kirovograd-Nafta LLC, Crimea-Petrol LLC, Pirsan LLC, Trade-Trust LLC, Elefteria LLC, VKF Satek LLC, Stemv Group LLC v. The Russian Federation, PCA Case No. 2015-35",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "decided",
    status: { uk: "Остаточне рішення", en: "Final award" },
    year: 2015,
    amountUsd: 34600000,
    note: { uk: "PCA 2015-35", en: "PCA 2015-35" },
    pages: null,
    decisionUrl: "https://www.italaw.com/sites/default/files/case-documents/italaw16549.pdf",
    lit: false,
  },
  {
    id: "pca-26",
    num: 26,
    institutionId: "pca",
    name: "Everest Estate LLC, Edelveis-2000 PE, Fortuna CJSC and others v. The Russian Federation, PCA Case No. 2015-36",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "progress",
    status: { uk: "Повернуто на новий розгляд", en: "Remitted for rehearing" },
    year: 2015,
    amountUsd: 159000000,
    note: { uk: "PCA 2015-36", en: "PCA 2015-36" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-27",
    num: 27,
    institutionId: "pca",
    name: "Limited Liability Company Lugzor, Limited Liability Company Libset, Limited Liability Company Ukrinterinvest, Public Joint Stock Company DniproAzot, Limited Liability Company Aberon Ltd v. The Russian Federation, PCA Case No. 2015-29",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "decided",
    status: { uk: "Рішення винесено", en: "Judgment delivered" },
    year: 2015,
    amountUsd: null,
    note: { uk: "PCA 2015-29", en: "PCA 2015-29" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-28",
    num: 28,
    institutionId: "pca",
    name: "JSC DTEK Krymenergo v. The Russian Federation, PCA Case No. 2018-41",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "enforcement",
    status: { uk: "Виконання зупинено", en: "Enforcement stayed" },
    year: 2018,
    amountUsd: 207800000,
    note: { uk: "PCA 2018-41", en: "PCA 2018-41" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-29",
    num: 29,
    institutionId: "pca",
    name: "National Power Company Ukrenergo v. The Russian Federation, PCA Case No. 2020-17",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "progress",
    status: { uk: "Розгляд по суті", en: "Merits pending" },
    year: 2020,
    amountUsd: 580000000,
    note: { uk: "PCA Paris · заявлена", en: "PCA Paris · claimed" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-30",
    num: 30,
    institutionId: "pca",
    name: "NNEGC Energoatom v. The Russian Federation (II)",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "progress",
    status: { uk: "До арбітражу", en: "Heading to arbitration" },
    year: 2023,
    amountUsd: 3000000000,
    note: { uk: "Заявлена", en: "Claimed" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "pca-31",
    num: 31,
    institutionId: "pca",
    name: "PrJSC Ukrhydroenergo v. The Russian Federation",
    type: { uk: "BIT арбітраж", en: "Investment (BIT) arbitration" },
    statusKey: "progress",
    status: { uk: "Призупинено", en: "Suspended" },
    year: 2024,
    amountUsd: 2500000000,
    note: { uk: "Заявлена", en: "Claimed" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "nl-32",
    num: 32,
    institutionId: "nl",
    name: "PPS v Girkin, Dubinskiy, Pulatov, Kharchenko (MH17)",
    type: { uk: "Нац. кримінальне", en: "National criminal" },
    statusKey: "decided",
    status: { uk: "Остаточний вирок", en: "Final verdict" },
    year: 2020,
    amountUsd: null,
    note: { uk: "NL · ECLI:NL:RBDHA", en: "NL · ECLI:NL:RBDHA" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "nl-33",
    num: 33,
    institutionId: "nl",
    name: "JIT MH17 follow-on",
    type: { uk: "Нац. кримінальне", en: "National criminal" },
    statusKey: "progress",
    status: { uk: "Призупинено", en: "Suspended" },
    year: 2014,
    amountUsd: null,
    note: { uk: "JIT MH17", en: "JIT MH17" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "nl-34",
    num: 34,
    institutionId: "nl",
    name: "Russia v Naftogaz et al. (Hoge Raad, скасування)",
    type: { uk: "Нац. цивільне", en: "National civil" },
    statusKey: "decided",
    status: { uk: "Арбітраж залишено", en: "Arbitration upheld" },
    year: 2023,
    amountUsd: null,
    note: { uk: "HR:2024:1810", en: "HR:2024:1810" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "nl-35",
    num: 35,
    institutionId: "nl",
    name: "Russia v Belbek/Kolomoisky (Hoge Raad)",
    type: { uk: "Нац. цивільне", en: "National civil" },
    statusKey: "decided",
    status: { uk: "Арбітраж залишено", en: "Arbitration upheld" },
    year: 2022,
    amountUsd: null,
    note: { uk: "HR 2024", en: "HR 2024" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "nl-36",
    num: 36,
    institutionId: "nl",
    name: "Russia v PrivatBank/Finilon (Hoge Raad)",
    type: { uk: "Нац. цивільне", en: "National civil" },
    statusKey: "decided",
    status: { uk: "Арбітраж залишено", en: "Arbitration upheld" },
    year: 2022,
    amountUsd: null,
    note: { uk: "HR 2024", en: "HR 2024" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "nl-37",
    num: 37,
    institutionId: "nl",
    name: "Russia v Everest Estate (Hoge Raad)",
    type: { uk: "Нац. цивільне", en: "National civil" },
    statusKey: "progress",
    status: { uk: "Повернуто до апеляції", en: "Remitted to appeal" },
    year: 2022,
    amountUsd: null,
    note: { uk: "HR 2024", en: "HR 2024" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "fi-38",
    num: 38,
    institutionId: "fi",
    name: "Finland v Yan Petrovsky (UJ, Rusich)",
    type: { uk: "Нац. кримінальне", en: "National criminal" },
    statusKey: "decided",
    status: { uk: "Вирок", en: "Verdict" },
    year: 2024,
    amountUsd: null,
    note: { uk: "Helsinki · перше UJ засудження", en: "Helsinki · first universal-jurisdiction conviction" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "lt-39",
    num: 39,
    institutionId: "lt",
    name: "Lithuania v Gadzhimagomedov (UJ, катування)",
    type: { uk: "Нац. кримінальне", en: "National criminal" },
    statusKey: "progress",
    status: { uk: "До суду", en: "Heading to trial" },
    year: 2025,
    amountUsd: null,
    note: { uk: "Vilnius · перша екстрадиція", en: "Vilnius · first extradition" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
  {
    id: "eu-40",
    num: 40,
    institutionId: "eu",
    name: "EU / Belgium — frozen assets of the Russian Central Bank (Euroclear)",
    type: { uk: "Виконавче рішення", en: "Enforcement measure" },
    statusKey: "frozen",
    status: { uk: "Заморожено безстроково", en: "Frozen indefinitely" },
    year: 2022,
    amountUsd: 210000000000,
    note: { uk: "Euroclear €210 млрд", en: "Euroclear €210bn" },
    pages: null,
    decisionUrl: null,
    lit: false,
  },
];
